export const search = [
  {
    id: 1,
    title: 'food for adult and children',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.435,
    latitude: 7.715,
  },
  {
    id: 2,
    title: 'shelter',
    address: '117 Kenhdnsh lagoss State, nigeria',
    distance: '0.2',
    tag: 'shelter',
    longitude: 4.4241,
    latitude: 7.7163,
  },
  {
    id: 3,
    title: 'clothing',
    address: '117 Kenhdnsh lagoss Baltimore, MD 228292',
    distance: '0.2',
    tag: 'clothing',
    longitude: 4.4358,
    latitude: 7.7358,
  },
  {
    id: 4,
    title: 'food',
    address: '117 Kenhdnsh lagoss Nairobi Kenya, lagos State',
    distance: '0.2',
    tag: 'food',
    longitude: 4.4193,
    latitude: 7.7283,
  },
  {
    id: 5,
    title: 'food',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 7.7312,
    latitude: 4.4181,
  },
  {
    id: 6,
    title: 'food',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.4231,
    latitude: 7.7322,
  },
];

export const currentRequest = [
  {
    id: 1,
    title: 'food for adult and children',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.435,
    latitude: 7.715,
    postedOn: new Date(2020, 5, 11, 16),
  },
];

export const pastRequests = [
  {
    id: 1,
    title: 'food for adult and children',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.435,
    latitude: 7.715,
    postedOn: new Date(2020, 5, 11, 16),
    approved: true,
  },
  {
    id: 2,
    title: 'food for adult and children',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.435,
    latitude: 7.715,
    postedOn: new Date(2020, 5, 11, 16),
    approved: false,
  },
  {
    id: 3,
    title: 'food for adult and children',
    address: '117 Kenhdnsh lagoss jsjsjj',
    distance: '0.2',
    tag: 'food',
    longitude: 4.435,
    latitude: 7.715,
    postedOn: new Date(2020, 5, 11, 16),
    approved: false,
  },
];

export const profileData = {
  uuid: 1,
  firstName: 'lilly',
  lastName: 'anderson',
  email: 'l.anderson@gmail.com',
  mobile: 2348090755201,
  address: '117 Kenhdnsh lagoss jsjsjj',
  family: ['2 adults', '1 child'],
  allergies: ['milk', 'yoogurt', 'eggs'],
  clothing: ['s', 'xl', 'xxl'],
  requestSent: 15,
  password: '12345678',
};
